### PR TITLE
Fix #282

### LINKED ISSUE #282: possible huge performance regression in `batched_mul`
i'm still looking into the cause and quantifying the magnitude of the effect, but i think it is caused by https://github.com/FluxML/NNlib.jl/pull/271.  has anyone else observed this?

### PR DESCRIPTION
**Pull request by mcabbott**

### CODE REVIEW

File: test/batchedmul.jl [hunk 1]
```diff
@@ -119,17 +119,21 @@ end
     end
 end
 
+perm_12(A) = PermutedDimsArray(A, (2,1,3))
```
Comment (DhairyaLGandhi) [inline test/batchedmul.jl:122]: Can you move these inside the testset

Comment (mcabbott) [reply test/batchedmul.jl:122]: These don't depend on the T being looped over there. Seems clearer not to put them at the top of the file with all the other functions.
