### PR TITLE
Remove timer outputs as they mess with type inference

### LINKED ISSUE #125: Convolution is not inferable
e.g.
```julia
x = rand(10, 10, 3, 2)
w = rand(2, 2, 3, 4)
@code_typed conv(x, w, DenseConvDims(x, w)) # AbstractArray{yT, 4} where yT
```

@staticfloat any idea what might be going wrong here?

### PR DESCRIPTION
**Pull request by avik-pal**
@staticfloat I am removing the TimerOutputs given they mess with the type inference. Let me know if there are any other possible solutions to this issue
Fixes #125

### CODE REVIEW

File: src/NNlib.jl [hunk 1]
```diff
@@ -1,9 +1,6 @@
 module NNlib
 using Requires, TimerOutputs
```
Comment (staticfloat) [inline src/NNlib.jl]: Don't forget this one.  :P

**Comment by staticfloat** [comment]
Looks like you missed some in `src/nnpack/impl.jl`

**Comment by staticfloat** [comment]
Also, let's add tests to ensure that `conv()` is inferred.

**Comment by staticfloat** [comment]
Tada!  Passing tests.  Excellent.
