### PR TITLE
Fixes #293 and #294

### LINKED ISSUE #293: rrule for `pad_constant` fails when using (l1, r1, ..., ln, rn) padding
## Problem
When executing the following snippet:

```julia
using Zygote, NNlib

upad, ∂upad = Zygote.pullback(u -> NNlib.pad_zeros(u, (0, 1, 0, 1)), u)
upad # <= everything looks correct
∂upad(ones(size(upad)))
```

```julia
MethodError: no method matching size_and_center(::Array{Float64,2}, ::Tuple{Tuple{Int64,Int64},Tuple{Int64,Int64}})
Closest candidates are:
  size_and_center(::Any, ::Tuple{Vararg{Int64,N}}) where N at /home/tor/.julia/packages/NNlib/uX1eA/src/padding.jl:157

Stacktrace:
 [1] (::NNlib.var"#pad_constant_pullback#263"{2,Colon,Array{Float64,2},NTuple{4,Int64}})(::Array{Float64,2}) at /home/tor/.julia/packages/NNlib/uX1eA/src/padding.jl:170
 [2] ZBack at /home/tor/.julia/packages/Zygote/KpME9/src/compiler/chainrules.jl:77 [inlined]
 [3] (::Zygote.var"#kw_zpullback#40"{NNlib.var"#pad_constant_pullback#263"{2,Colon,Array{Float64,2},NTuple{4,Int64}}})(::Array{Float64,2}) at /home/tor/.julia/packages/Zygote/KpME9/src/compiler/chainrules.jl:103
 [4] #pad_zeros#242 at /home/tor/.julia/packages/NNlib/uX1eA/src/padding.jl:10 [inlined]
 [5] pad_zeros at /home/tor/.julia/packages/NNlib/uX1eA/src/padding.jl:10 [inlined]
 [6] #65 at ./In[62]:1 [inlined]
 [7] (::Zygote.var"#41#42"{typeof(∂(#65))})(::Array{Float64,2}) at /home/tor/.julia/packages/Zygote/KpME9/src/compiler/interface.jl:40
 [8] top-level scope at In[64]:1
 [9] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1091
```

Seems like the issue is the line https://github.com/FluxML/NNlib.jl/blob/master/src/padding.jl#L170 which calls `size_and_center` which doesn't support `NTuple{N, NTuple{2, Int}}` despite `gen_pad` seeming only returning those formats https://github.com/FluxML/NNlib.jl/blob/master/src/padding.jl#L128-L145?

## Solution
Seems like adding the following implementation of `size_and_center` should fix it:

```julia
function size_and_center(x, pad::NTuple{N,NTuple{2, Int}}) where N
  sz = ntuple(i -> pad[i][1] + pad[i][2], N) .+ size(x)
  center = broadcast((x,y) -> x .+ y, axes(x), ntuple(i -> pad[i][2], N))
  sz, center
end
```

I can make a PR if this seems reasonable.

### PR DESCRIPTION
**Pull request by torfjelde**
This PR fixes #293 and #294, and in the process moves to using only `((l1, r1), ..., (ln, rn))` representation of padding internally instead of both that and `(l1, r1, ..., ln, rn)`. This means that we can simplify the codebase a bit.

### CODE REVIEW

**Comment by CarloLucibello** [comment]
Thanks for this! Can you add tests for fixed issues?

**Comment by torfjelde** [comment]
Ah, yes ofc! I did an hour ago but forgot to push. Did so now :+1:

**Comment by DhairyaLGandhi** [comment]
We might want to hold on to the function so we can get the correct length tuple when we don't have all the dims and padding information.

**Comment by DhairyaLGandhi** [comment]
Could we also test for padding vectors?

File: test/padding.jl [hunk 1]
```diff
@@ -35,7 +38,10 @@
 
   @test size(pad_constant(x, 1, dims = 1)) == (4,2,2)
 
+  @test all(pad_zeros(randn(2), (1, 2))[[1, 4, 5]] .== 0)
+
   gradtest(x -> pad_constant(x, 2), rand(2,2,2))
+  gradtest(x -> pad_constant(x, (2, 1, 1, 2)), rand(2,2))
```
Comment (DhairyaLGandhi) [inline test/padding.jl:44]:
```suggestion
  gradtest(x -> pad_constant(x, (2, 1, 1, 2)), rand(2,2))
  gradtest(x -> pad_constant(x, (2, 1,)), rand(2))
```

**Review by DhairyaLGandhi — COMMENTED** [review]
I've added a gradtesr for vectors as well

**Comment by DhairyaLGandhi** [comment]
Thanks!
